### ISSUE TITLE
footer added and font updated

### ISSUE THREAD

**Issue by Utkarsh1504** [nhcommunity/homepage#15]
As you can see in the pull request which I will be created in a while. I have added the footer on the home page.
also just for the experimenting I just add some of `<h1>hi there<h1>` inside of index.html file
you can delete them while adding the content.

**Comment by nhcarrigan** [comment]
Hi there,

Thank you for your interest in contributing to our project. When opening an issue, it is important that you follow the issue template as they are designed to walk you through the information we need to triage your issue.

If you are interested in contributing code changes, you do not need to open an issue first if you provide clear context in your pull request as to why the changes are necessary and relevant.

I am going to go ahead and close this issue. We would gladly welcome future issues from you.
