### ISSUE TITLE
[FEAT] Favicon Missing

### ISSUE THREAD

**Issue by AnirudhPanda** [nhcommunity/homepage#17]
# Feature Request

## Is your feature request related to a problem? Please describe:

A favicon adds to the cleaner look of the site as well as helps in Search Engine Optimization

## Describe the solution you'd like

Update the favicon provided an image or text and shall convert it into  .ico file and add it to the website

**Comment by Skyhero-admin** [comment]
what are y'all using for the favicon ?

**Comment by AnirudhPanda** [comment]
Hey, @nhcarrigan I can work on this issue, provided what kind of favicon you want:

- Image based
- Text Based
- Emoji based

**Comment by nhcarrigan** [comment]
It's not what I want, it's what y'all want as the community 😁

**Comment by AnirudhPanda** [comment]
> It's not what I want, it's what y'all want as the community 😁

Cool. Let me make something and you guys can check
