### ISSUE TITLE
[FEAT] Sticky Nav

### ISSUE THREAD

**Issue by DennaGrey** [nhcommunity/homepage#24]
### What feature would you like to see?

Hello awesome nhcarrigan community! 

To help make our new website easy to navigate, we hope to implement a sticky navigation bar, so that as you scroll through you can still easily jump from one section to the next. 

Basically, we need the nav bar to travel with you as you begin to scroll. "Stick"ing it to the screen as you peruse our website, that way you can easily jump from the middle of one section to a completely different one.

As always suggestions are welcome!

**Comment by VirajS00** [comment]
I think, this is a good idea, it will make it easier to navigate. Can I work on this issue?

**Comment by nhcarrigan** [comment]
Sure!

**Comment by VirajS00** [comment]
one problem with this is that there is no active state of the menu items when you go to a particular section.
