### ISSUE TITLE
[FEAT] - Recognise Our Moderators

### ISSUE THREAD

**Issue by nhcarrigan** [nhcommunity/homepage#3]
# Feature Request

## Is your feature request related to a problem? Please describe:

As a user, I should see a page which recognises the moderators of our community. This page should include information about each moderator, a link to their website/profile/whichever they'd like.

## Describe the solution you'd like

We should create a new file (`moderators.html`, maybe) within the `views` directory for this page.

**Comment by starlightknown** [comment]
Can I work on this too? I see a PR but we can add some styling and some cards to display the members

**Comment by nhcarrigan** [comment]
Yes go ahead! The open PR adds a blank file and has not been updated yet.

**Comment by starlightknown** [comment]
Thank you

**Comment by Evavic44** [comment]
> Can I work on this too? I see a PR but we can add some styling and some cards to display the members

Hello Karuna, are you working on this or should I make a PR to fix this?

**Comment by Sonichigo** [comment]
Can i work on this?

**Comment by Panquesito7** [comment]
> Can I work on this?

I think you can as long as nobody else is working on this. 🙂

**Comment by Sonichigo** [comment]
> > Can I work on this?
> 
> I think you can as long as nobody else is working on this. 🙂

PR has been made, so i guess not maybe 😅

**Comment by ps-19** [comment]
Hi @nhcarrigan i have few questions : 
1) how to know all moderators of any repository?
2) will moderator.html be static or dynamic?
Thank you.

**Comment by Evavic44** [comment]
> 
> 
> Hi @nhcarrigan i have few questions :
> 
>     1. how to know all moderators of any repository?
> 
>     2. will moderator.html be static or dynamic?
>        Thank you.

Follow this link to see a list of all the moderators: [Nhcommunity Moderators](https://github.com/orgs/nhcommunity/teams/moderators/members)

**Comment by ps-19** [comment]
@Evavic44 kindly visit the link before posting.

**Comment by ps-19** [comment]
@Evavic44 link is broken.

**Comment by Evavic44** [comment]
That's weird. It works for me. https://github.com/orgs/nhcommunity/teams/moderators

**Comment by nhcarrigan** [comment]
We want to include our Discord moderators as well, who may not be on GitHub. 🙂

**Comment by Panquesito7** [comment]
> > > Can I work on this?
> > 
> > 
> > I think you can as long as nobody else is working on this. 🙂
> 
> PR has been made, so i guess not maybe 😅

That PR was kind of invalid, as the file added didn't have any content.

**Comment by Panquesito7** [comment]
> That's weird. It works for me. https://github.com/orgs/nhcommunity/teams/moderators

That's because people outside the organization can't see it.

**Comment by Evavic44** [comment]
Ohhh.... @Panquesito7
