### ISSUE TITLE
[FEAT] Add scribes(translators)

### ISSUE THREAD

**Issue by j-dogcoder** [nhcommunity/homepage#43]
### What feature would you like to see?

Add translators to website

**Comment by nhcarrigan** [comment]
At this time, the translation is specifically scoped to Becca, and translators will be added to a command there (and likely the documentation site) as languages are released.

Would be happy to consider adding translators to the community page, but IMHO doesn't make sense at this time as we only have one project in active translation.

**Comment by j-dogcoder** [comment]
Fair enough.
