### ISSUE TITLE
[BUG] Section not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [nhcommunity/homepage#47]
### What bug did you encounter?

Section "Becca" on homepage not working.
https://community.nhcarrigan.com/index.html#becca

### What did you expect to happen?

1. Tap "Becca"
2. Go to "Becca" page

**Comment by nhcarrigan** [comment]
Yeah there isn't really a Becca section to link to.

We should update the link in the nav bar to point to https://www.beccalyria.com, with `target="_blank"` so it opens in a new tab.

**Comment by KendallDoesCoding** [comment]
> Yeah there isn't really a Becca section to link to.
> 
> We should update the link in the nav bar to point to https://www.beccalyria.com, with `target="_blank"` so it opens in a new tab.

Ok cool. Btw, I can see a "Member" badge on your comment not "Owner" thought this was your organization?

**Comment by Panquesito7** [comment]
> > Yeah there isn't really a Becca section to link to.
> > We should update the link in the nav bar to point to https://www.beccalyria.com, with `target="_blank"` so it opens in a new tab.
> 
> Ok cool. Btw, I can see a "Member" badge on your comment not "Owner" thought this was your organization?

_Owner_ only applies when you're the owner of a repository of _yours_. This is their organization, but it will show up as _Member_ as there can be multiple administrators/owners. 🙂
