### ISSUE TITLE
[FEAT] Hamburger menu style for the navbar

### ISSUE THREAD

**Issue by AnujSsStw** [nhcommunity/homepage#51]
### What feature would you like to see?

Hey, can I work on the hamburger menu style for the navbar for mobile styles? 
<img width="268" alt="opinion" src="https://user-images.githubusercontent.com/92370865/160868876-55bfdd42-916a-444d-9ac7-fc909a4c34ed.PNG">

**Comment by nhcarrigan** [comment]
Yes, go ahead. 🙂
