### ISSUE TITLE
[BUG] Remove Whisperdawn from the moderation team

### ISSUE THREAD

**Issue by Panquesito7** [nhcommunity/homepage#55]
### What bug did you encounter?

Whisperdawn appears not to be on the moderation team anymore. They should be removed.

### What did you expect to happen?

Remove Whisperdawn from the moderation team.

### Screenshots

![image](https://user-images.githubusercontent.com/51391473/168899332-94390e32-ddae-49dd-8a2a-d56f2b146eb7.png)

### Additional information

There are a few invalid images. That fits for another issue, of course, but should be fixed, as soon as possible.

**Comment by nhcarrigan** [comment]
Opening this up for first timers.

**Comment by NerdyChara** [comment]
I think this issue was already completed
