### ISSUE TITLE
[FEAT] Nav Tabs & Sections

### ISSUE THREAD

**Issue by DennaGrey** [nhcommunity/homepage#6]
# Feature Request

## Is your feature request related to a problem? Please describe:

To start our website we need to make a series of decisions. One of those, needs to be how many tabs are there going to be on the nav bar, and what are those tabs going to be?

Generally we want the tabs to be one word, or otherwise short so please keep that in mind while we go through this process. 

We will also need to actually write out the info that will be displayed in these tabs. 

## Describe the solution you'd like

We had two good suggestions already, 
"
- Help people on their programming journey
- Gaming discussion and events
- Becca"

and 

" info about the community, community goals, values and then a section for "Who is nhcarrigan?"" 

Combining these two could be in our best interest. 

I'm suggesting: Discussion, Gaming, Becca, Community, Goals & Events and About NhCarrigan

and we need to choose who will write each section. 
## Additional context
Also looking for any additional suggestions, tweaks, anything

**Comment by Skyhero-admin** [comment]
I have added some info in this html file https://github.com/Skyhero-admin/homepage . I've taken some from nick's portfolio though. I haven't started styling it yet because I still want to get some idea about the design .

**Comment by nhcarrigan** [comment]
@Skyhero-admin you should open a pull request so people can start providing feedback. 🙂

**Comment by starlightknown** [comment]
I can make a nav bar for this, horizontal one with tabs in given suggestions

> I'm suggesting: Discussion, Gaming, Becca, Community, Goals & Events and About NhCarrigan

**Comment by nhcarrigan** [comment]
Love it!

**Comment by starlightknown** [comment]
alright I'll start working on it

**Comment by Evavic44** [comment]
> # Feature Request
> ## Is your feature request related to a problem? Please describe:
> To start our website we need to make a series of decisions. One of those, needs to be how many tabs are there going to be on the nav bar, and what are those tabs going to be?
> 
> Generally we want the tabs to be one word, or otherwise short so please keep that in mind while we go through this process.
> 
> We will also need to actually write out the info that will be displayed in these tabs.
> 
> ## Describe the solution you'd like
> We had two good suggestions already,
> "
> 
> * Help people on their programming journey
> * Gaming discussion and events
> * Becca"
> 
> and
> 
> " info about the community, community goals, values and then a section for "Who is nhcarrigan?""
> 
> Combining these two could be in our best interest.
> 
> I'm suggesting: Discussion, Gaming, Becca, Community, Goals & Events and About NhCarrigan
> 
> and we need to choose who will write each section.
> 
> ## Additional context
> Also looking for any additional suggestions, tweaks, anything

Can we turn the list of things we need to do in this issue into a checklist, so we check them as appropriate?
