### ISSUE TITLE
[OTHER] [STYLE] Text inside our community section looks kinda congested

### ISSUE THREAD

**Issue by muditchoudhary** [nhcommunity/homepage#65]
### What would you like to share?

# The issue
the texts inside the [our community, gaming, our discussions, who is nhcarrigan] look congested or packed tightly. I think It becomes a little hard to read the text. I think there should be some line spacing between the texts. 

# Screenshots
I tried to just play around in the dev tools and add a line-height of 25px to the h3 tag inside the out community section. I think the text in the after image looks easier to read.

### Before
![Screenshot from 2022-09-30 14-35-20](https://user-images.githubusercontent.com/74391865/193238881-bc5ca1d2-8ab1-4aa6-836b-1cd77c9058d0.png)

### After
![Screenshot from 2022-09-30 14-33-39](https://user-images.githubusercontent.com/74391865/193238954-ae9b9179-6569-4a3b-a82c-7a631098a801.png)

# Proposed Changes
I would like to add some line-height to the texts inside the following section above so that there is some space between texts.

**Comment by naomi-lgbt** [comment]
Sure, this seems like a good idea. We'll open this up for first timers.

**Comment by muditchoudhary** [comment]
Can I  work on this? Or is it best for new people who are learning?

**Comment by naomi-lgbt** [comment]
Go for it!

**Comment by muditchoudhary** [comment]
Hey, @naomi-lgbt does this issue also count for the hacktoberfest? just want to clarify.
