### ISSUE TITLE
[FEAT]Discussion for information on the landing page

### ISSUE THREAD

**Issue by Skyhero-admin** [nhcommunity/homepage#7]
# Feature Request

## Is your feature request related to a problem? Please describe:

It would be good to get some feedback on the current information for the landing page 
I've some info in the index.html file here https://github.com/Skyhero-admin/homepage

## Describe the solution you'd like
If you have any sugestions to add or if something doesn't seem right and should be removed then please do let me know 😅

Also It's still not styled yet so I need some ideas for it

**Comment by nhcarrigan** [comment]
My recommendation would be to open a pull request so we can pull down the changes easier and use GitHub's UI to provide feedback.

**Comment by Skyhero-admin** [comment]
ohk

**Comment by Skyhero-admin** [comment]
Should I close this issue then ?
